### ISSUE TITLE
Lots of compilation warnings

### ISSUE THREAD

**Issue by bhaible** [derekp7/snebu#12]
Hi,

I wanted to make use of the "Backing up to a remote server" use-case of snebu. Got it compiled on my NAS (a Linux/arm box), worked around the terrible ssh configuration of that box (by using sshpass), but the "snebu-client backup" command never writes any data files.
It does write a /share/HDA_DATA/bruno/snebu-backup/meta/snebu-catalog.db file.
But /share/HDA_DATA/bruno/snebu-backup/vault/ remains empty.

I guess something in the submitfiles() function is not working right. But before running things with debugging printfs - I don't even have gdb on this machine -, I have the habit of looking at the "gcc -Wall" warnings.

This list of warnings is too long for me to go through.
[warnings-arm.txt](https://github.com/derekp7/snebu/files/887846/warnings-arm.txt)
[warnings-x86_64.txt](https://github.com/derekp7/snebu/files/887847/warnings-x86_64.txt)

**Comment by derekp7** [comment]
Thanks for bringing this to my attention.
The warnings on arm are mostly due to the C compiler having default warnings cranked up higher.  I've fixed this by replicating this on my Fedora dev environment, and rewriting code to clear up all the warnings.  Also have ran the new code through Valgrind to help eliminate any memory leaks or other issues.

Currently tested on multiple distributions, (Debian/Ubuntu, Fedora, Centos) along with testing on a Raspberry Pi.
