### ISSUE TITLE
SQL syntax error in expire

### ISSUE THREAD

**Issue by TripleEmcoder** [derekp7/snebu#8]
When running any expire command like stated in the docs:
`snebu expire -a 14 -r daily`

I get an error message like the following:
```
sqlite3_exec_return: 1
near "''": syntax error
insert or ignore into expirelist   select e.backupset_id from backupsets as e  left join (    select c.backupset_id, d.ranknum    from backupsets as c      inner join (        select a.backupset_id, count(*) as ranknum        from backupsets as a         inner join backupsets as b on (a.name = b.name)           and (a.retention = b.retention)           and (a.serial <= b.serial)       group by a.backupset_id        having ranknum <= 3      ) as d on (c.backupset_id = d.backupset_id)    order by c.name, d.ranknum  ) as f on e.backupset_id = f.backupset_id  where f.backupset_id is null and e.retention = 'daily' and e.serial < 1430241138''
```

**Comment by derekp7** [comment]
Ah, found the issue -- it was introduced when I put in some simplifications in the expiration logic, and my testing was done with specifying a hostname (in which case this bug doesn't manifest).

Just pushed the fix to the master branch, and did some minimal testing to make sure it works.  I'll be sure to add this to the full regression test suite.  If you want, go ahead and grab the current head of the master branch, otherwise I'll roll out a new release (tar and rpm) shortly.

**Comment by TripleEmcoder** [comment]
I was already using master so it was easy to confirm. There are no errors now when expiring.
