### ISSUE TITLE
Compression on the fly or using temp files?

### ISSUE THREAD

**Issue by TripleEmcoder** [derekp7/snebu#9]
Can you explain how snebu compresses files? Does it:
a) copy a file to the vault to a temp file and compress it to a second file there?
b) copy a file to /tmp and compress it there, then move it to the vault?
c) read the file from the source location and write a compressed stream straight to the destination in the vault, i.e. compress on-the-fly?
d) work in a different way?

This is important when using remotely mounted filesystems as vaults to avoid unnecessary transfers. I am experiencing not -so -great performance in this scenario which makes me wonder.

**Comment by derekp7** [comment]
The data flow is divided up in a couple of sections:
1) An initial manifest of files to backup is created by running `find`, and sent to `snebu newbackup` -- which in turns returns a list of files that are required to complete the backup (filtering out files that is already in the vault, based on the file attributes -- size, owner, mod time, etc).

2) The file collection from the client is then done via tar.  This raw tar output is then piped as input into `snebu submitfiles`.  If it is calling `snebu` on a remote server over ssh, this feeds through `lzop` on the client side, then `lzop -d` on the server side before feeding it into `snebu submitfiles`.  Otherwise, if it is done local (and the vault itself is either an attached drive or something like a NFS mount), then compression isn't involved at that stage.

3) The function `submitfiles()` within the `snebu` binary processes the tar file headers, writes out records to the sqlite DB, and then passes the file data for the given tar record (representing a given file) through the lzo library to compress on-the-fly, and write out to the a temp file on disk.  This temp file is then renamed to filename based on the sha1 checksum of the uncompressed file contents.  (The rename should happen without moving any more data, as the temp file is written to the same filesystem as the final target, as the base of the vault directory).

So the short answer is c, on-the-fly compression, and the compressed output is written to a temp filename (such as /mnt/vault/[random-name]), then moved to the final file name (/mnt/vault/xx/xxxxxx....).

If you are getting bad performance, it could be from a couple items ... If the metadata directory is also on the remote filesystem, then sqlite could have performance issues there due to latency.  Secondly, if there are a lot of small files, again latency could cause that to have low performance when writing them out individually.  To solve this, I could have it package multiple smaller files into larger container files, although this would make file cleanup after expiration a bit tricky.  I'd probably have to handle this similar to how files on tape are handled (so I may move to this model once I add in tape library support).  For the first issue, the location of the sqlite3 DB, you could keep that local, then after the backup transfer a compressed copy of it to the backup media.  This is what I end up doing when using a USB disk as the vault (after the backup job, I do something like a logrotate on the compressed snebu-catalog.db.lzo file on target media, then `lzop </location/of/snebu-catalog.db >/mnt/metadata/snebu-catalog.db.lzo`).

Or, instead of writing to a mounted filesystem, you could set up a `backup` user on the remote server and use `snebu-client` with the `--backup-server` option

**Comment by TripleEmcoder** [comment]
Thanks for your fast and detailed answer. I believe that the current approach is correct, and my performance issues must be caused by something else.

Merging small files into larger archives could be a configurable option. Im my case I am using a FUSE mounted S3 filesystem, so purging from there would in practice require downloading the entire archive and then reuploading, so I would keep that disabled.

Thanks for the tips about DB storage and backup - I am doing things exactly as you described.

**Comment by derekp7** [comment]
Here's one quick test you can do -- tar up some directory, then pipe to another tar command to untar into the remote mount point, something like:

`time tar -cf - /source/directory | tar -C /mnt/target/directory -xf`

and see how long that takes, compared to untarring to a local drive.

Then do the same tar, but set the output to a single file on the target: 

`tar -cf /mnt/target/directory/testfile.tar /source/directory`

That would tell you if the problem is in writing individual files (of course, no compression is involved in either of these tests).

I'll see if I can work on some other ideas to more directly support cloud storage systems, probably involving D2D2C (disk to disk to cloud), which would at least avoid having to re-download/re-upload (it would involve some re-uploading, depending on how rapidly files expire out of the larger storage chunks, but this can even be kept to a minimum by playing around with what goes in which storage pool -- using almost the same algorithms as generational garbage collection algorithms).
